INSERT INTO icd10 (code, description) VALUES
                                          ('G45.-', 'TIA/Schlaganfall/Hirnblutung'),
                                          ('G40.-', 'epileptischer Anfall'),
                                          ('F99', 'Psychiatrische Erkrankung'),
                                          ('R29.1', 'Meningismus'),
                                          ('F99', 'andere'),
                                          ('I61.-', 'Hirnblutung'),
                                          ('I60.-', 'Subarachnoidale Blutung'),
                                          ('G04.-', 'Meningitis/Enzephalitis'),
                                          ('F43.0', 'akute psych. Belastungsreaktion'),
                                          ('F99', 'Suchtkrankheit'),
                                          ('T25.0', 'Knöchel'),
                                          ('T25.0', 'Fuß/Zehe'),
                                          ('R55', 'Kollaps/Synkope'),
                                          ('R57.9', 'Schock'),
                                          ('I21.-', 'Herzinfarkt'),
                                          ('I50.-', 'Herzinsuffizienz'),
                                          ('I20.-', 'Angina Pectoris'),
                                          ('R07.4', '(akuter) Thoraxschmerz'),
                                          ('I49.-', 'Rhythmusstörung (bedrohlich)'),
                                          ('I50.1', 'Linksherz-Insuffizienz'),
                                          ('I10', 'hypertensive RR-Entgleisung'),
                                          ('I26.-', 'Lungenembolie'),
                                          ('I74.-', 'arterielle Embolie'),
                                          ('I73.9', 'periph. Durchblutungsstörung'),
                                          ('I82.-', 'venöse Thrombose'),
                                          ('J81', 'Lungenödem'),
                                          ('I99', 'andere'),
                                          ('I10', 'Hypertonie'),
                                          ('J45', 'Asthma'),
                                          ('J69.8', 'Aspiration'),
                                          ('J22', 'Atemwegsinfekt'),
                                          ('J18.9', 'Pneumonie'),
                                          ('J93.9', 'Pneumothorax'),
                                          ('J98.-', 'andere'),
                                          ('J44.9', 'COPD'),
                                          ('J96.9', 'respiratorische Insuffizienz'),
                                          ('R10.0', 'akutes Abdomen'),
                                          ('R10.4', 'Kolik'),
                                          ('K92.2', 'gastrointestinale Blutung'),
                                          ('R17', 'Ikterus'),
                                          ('K92.-', 'andere'),
                                          ('T50.9', 'Medikamente'),
                                          ('F10.0', 'Alkohol'),
                                          ('F19.5', 'Drogen'),
                                          ('A05.-', 'Lebensmittel'),
                                          ('T59.9', 'Rauchgas'),
                                          ('T65.9', 'chemische Substanzen'),
                                          ('T65.9', 'andere'),
                                          ('E14.-', 'Diabetes mellitus'),
                                          ('E07.-', 'Endokrine Krise'),
                                          ('N18.-', 'Niereninsuffizienz'),
                                          ('K72.-', 'Leberinsuffizienz'),
                                          ('E88.-', 'andere'),
                                          ('E88.-', 'Exicose'),
                                          ('R56.0', 'Fieberkrampf'),
                                          ('J05.0', 'Pseudokrupp/Laryngitis'),
                                          ('J05.-', 'Epiglottitis'),
                                          ('T65.9', 'Toxikose'),
                                          ('R95', 'SIDS'),
                                          ('B99', 'Kinderinfektionskrankheit'),
                                          ('B99', 'andere'),
                                          ('O80.-', 'Geburt'),
                                          ('O06.9', 'Abortus'),
                                          ('N94.9', 'Tubaria'),
                                          ('N93.9', 'vaginale Blutung'),
                                          ('N94.9', 'andere'),
                                          ('O60', 'Frühgeburt'),
                                          ('D43.9', 'nicht zuordenbar Tumor'),
                                          ('D43.9', 'ZNS (Zentralnervensystem)'),
                                          ('R07.4', 'Thorax'),
                                          ('R10.0', 'Abdomen'),
                                          ('N94.9', 'Gyn (Gynäkologie)'),
                                          ('nicht zuordenbar andere Erkrankungen', 'nicht zuordenbar andere Erkrankungen'),
                                          ('D64.-', 'Anämien versch. Ursache'),
                                          ('G93.-', 'angeborene cerebr. Störung'),
                                          ('M13.9', 'Arthropathien versch. Ursache'),
                                          ('T14.1', 'Bißverletzung durch Tiere'),
                                          ('T42', 'Bronchitis'),
                                          ('M51.9', 'Discus Protr/Prolaps'),
                                          ('R04.4', 'Epistaxis'),
                                          ('J06.9', 'grippaler Infekt'),
                                          ('N39.0', 'Harnwegsinfektion'),
                                          ('K75.-', 'Hepatitis'),
                                          ('R046.4', 'Hyperventilationstet.'),
                                          ('K56.7', 'Ileus'),
                                          ('T63.4', 'Insektenstich'),
                                          ('I83.9', 'Krampfaderblutung'),
                                          ('C95.9', 'Leukämie'),
                                          ('G35', 'Multiple Sklerose'),
                                          ('H81.0', 'Meniere Syndrom'),
                                          ('N04.-', 'Nephritis'),
                                          ('L03.9', 'Phlegmone u. Abszesse'),
                                          ('R09.1', 'Pleuritis'),
                                          ('A02.-', 'Salmonellose'),
                                          ('E07.-', 'Schilddrüsenstörung'),
                                          ('N94.9', 'Tubaria'),
                                          ('A15.9', 'Tuberkulose'),
                                          ('K26.-', 'Ulcus d. Magen-Darmtr.'),
                                          ('L50.9', 'Urticaria'),
                                          ('M54.4', 'Lumbago'),
                                          ('R96.-', 'Exitus'),
                                          ('nicht zuordenbar Kontrollfahrt/zur Behandlung', 'nicht zuordenbar Kontrollfahrt/zur Behandlung'),
                                          ('R53', 'Allgemeine Schwächezustand'),
                                          ('R11', 'Erbrechen'),
                                          ('R42', 'Vertigo'),
                                          ('Z03.9', 'ohne Befund'),
                                          ('S09.7', 'Schädel'),
                                          ('S05.9', 'Augen'),
                                          ('S09.9', 'Nase'),
                                          ('S14.2', 'Halswirbelsäule'),
                                          ('S49.9', 'Schulter'),
                                          ('S29.9', 'Thorax'),
                                          ('S24.2', 'Brustwirbelsäule'),
                                          ('S49.-', 'Oberarm'),
                                          ('S57.0', 'Ellenbogen'),
                                          ('S59.9', 'Unterarm'),
                                          ('S69.9', 'Hand/Finger'),
                                          ('S34.2', 'Lendenwirbelsäule'),
                                          ('S39.7', 'Abdomen'),
                                          ('S79.-', 'Becken/Hüfte'),
                                          ('S30.2', 'Genitalbereich'),
                                          ('S79.-', 'Oberschenkel'),
                                          ('S83.7', 'Knie'),
                                          ('S89.-', 'Unterschenkel'),
                                          ('S99.7', 'Knöchel'),
                                          ('S99.9', 'Fuß/Zehen'),
                                          ('T01.0', 'Schnittwunde Schädel'),
                                          ('S01.1', 'Schnittwunde Augen'),
                                          ('S01.2', 'Schnittwunde Nase'),
                                          ('Halswirbelsäule', 'Schnittwunde Halswirbelsäule'),
                                          ('S41.0', 'Schnittwunde Schulter'),
                                          ('S21.-', 'Schnittwunde Thorax'),
                                          ('S41.1', 'Schnittwunde Oberarm'),
                                          ('S51.0', 'Schnittwunde Ellenbogen'),
                                          ('S51.-', 'Schnittwunde Unterarm'),
                                          ('S61.-', 'Schnittwunde Hand/Finger'),
                                          ('Lendenwirbelsäule', 'Schnittwunde Lendenwirbelsäule'),
                                          ('S31.8', 'Schnittwunde Abdomen'),
                                          ('S31.0', 'Schnittwunde Becken/Hüfte'),
                                          ('S31.4', 'Schnittwunde Genitalbereich'),
                                          ('S71.1', 'Schnittwunde Oberschenkel'),
                                          ('S81.0', 'Schnittwunde Knie'),
                                          ('S81.-', 'Schnittwunde Unterschenkel'),
                                          ('S91.0', 'Schnittwunde Knöchel'),
                                          ('S91.3', 'Schnittwunde Fuß/Zehen'),
                                          ('T14.1', 'Schusswunde Schädel'),
                                          ('T14.1', 'Schusswunde Augen'),
                                          ('T14.1', 'Schusswunde Nase'),
                                          ('T14.1', 'Schusswunde Halswirbelsäule'),
                                          ('T14.1', 'Schusswunde Schulter'),
                                          ('T14.1', 'Schusswunde Thorax'),
                                          ('T14.1', 'Schusswunde Brustwirbelsäule'),
                                          ('T14.1', 'Schusswunde Oberarm'),
                                          ('T14.1', 'Schusswunde Ellenbogen'),
                                          ('T14.1', 'Schusswunde Unterarm'),
                                          ('T14.1', 'Schusswunde Hand/Finger'),
                                          ('T14.1', 'Schusswunde Lendenwirbelsäule'),
                                          ('T14.1', 'Schusswunde Abdomen'),
                                          ('T14.1', 'Schusswunde Becken/Hüfte'),
                                          ('T14.1', 'Schusswunde Genitalbereich'),
                                          ('T14.1', 'Schusswunde Oberschenkel'),
                                          ('T14.1', 'Schusswunde Knie'),
                                          ('T14.1', 'Schusswunde Unterschenkel'),
                                          ('T14.1', 'Schusswunde Knöchel'),
                                          ('T14.1', 'Schusswunde Fuß/Zehen'),
                                          ('T02.00', 'Geschlossene Fraktur Schädel'),
                                          ('S02.20', 'Geschlossene Fraktur Augen'),
                                          ('S12.70', 'Geschlossene Fraktur Nase'),
                                          ('S12.70', 'Geschlossene Fraktur Halswirbelsäule'),
                                          ('S42.90', 'Geschlossene Fraktur Schulter'),
                                          ('T02.00', 'Geschlossene Fraktur Thorax'),
                                          ('S32.7', 'Geschlossene Fraktur Brustwirbelsäule'),
                                          ('S42.80', 'Geschlossene Fraktur Oberarm'),
                                          ('S52.00', 'Geschlossene Fraktur Ellenbogen'),
                                          ('S52.-', 'Geschlossene Fraktur Unterarm'),
                                          ('S62.0', 'Geschlossene Fraktur Hand/Finger'),
                                          ('S32.00', 'Geschlossene Fraktur Lendenwirbelsäule'),
                                          ('S32.8', 'Geschlossene Fraktur Abdomen'),
                                          ('S32.8', 'Geschlossene Fraktur Becken/Hüfte'),
                                          ('S72.90', 'Geschlossene Fraktur Oberschenkel'),
                                          ('S82.00', 'Geschlossene Fraktur Knie'),
                                          ('S82.80', 'Geschlossene Fraktur Unterschenkel'),
                                          ('S82.60', 'Geschlossene Fraktur Knöchel'),
                                          ('S92.70', 'Geschlossene Fraktur Fuß/Zehen'),
                                          ('T02.01', 'Offene Fraktur Schädel'),
                                          ('S02.21', 'Offene Fraktur Augen'),
                                          ('S12.71', 'Offene Fraktur Nase'),
                                          ('S12.71', 'Offene Fraktur Halswirbelsäule'),
                                          ('S42.91', 'Offene Fraktur Schulter'),
                                          ('T02.01', 'Offene Fraktur Thorax'),
                                          ('S32.7', 'Offene Fraktur Brustwirbelsäule'),
                                          ('S42.81', 'Offene Fraktur Oberarm'),
                                          ('S52.1', 'Offene Fraktur Ellenbogen'),
                                          ('S52.01', 'Offene Fraktur Unterarm'),
                                          ('S62.0', 'Offene Fraktur Hand/Finger'),
                                          ('S32.01', 'Offene Fraktur Lendenwirbelsäule'),
                                          ('S32.8', 'Offene Fraktur Abdomen'),
                                          ('S32.8', 'Offene Fraktur Becken/Hüfte'),
                                          ('S72.91', 'Offene Fraktur Oberschenkel'),
                                          ('S82.01', 'Offene Fraktur Knie'),
                                          ('S82.81', 'Offene Fraktur Unterschenkel'),
                                          ('S82.61', 'Offene Fraktur Knöchel'),
                                          ('S92.71', 'Offene Fraktur Fuß/Zehen'),
                                          ('S48.9', 'Amputation Schulter'),
                                          ('S28.1', 'Amputation Thorax'),
                                          ('S48.-', 'Amputation Oberarm'),
                                          ('S58.0', 'Amputation Ellenbogen'),
                                          ('S58.-', 'Amputation Unterarm'),
                                          ('S68.9', 'Amputation Hand/Finger'),
                                          ('Lendenwirbelsäule', 'Amputation'),
                                          ('Abdomen', 'Amputation'),
                                          ('S78.0', 'Amputation Becken/Hüfte'),
                                          ('S38.2', 'Amputation Genitalbereich'),
                                          ('S78.9', 'Amputation Oberschenkel'),
                                          ('S78.1', 'Amputation Knie'),
                                          ('S88.9', 'Amputation Unterschenkel'),
                                          ('S98.0', 'Amputation Knöchel'),
                                          ('S98.-', 'Amputation Fuß/Zehen'),
                                          ('S00.9', 'Prellung Schädel'),
                                          ('S05.1', 'Prellung Augen'),
                                          ('S00.3', 'Prellung Nase'),
                                          ('S20.2', 'Prellung Halswirbelsäule'),
                                          ('S40.0', 'Prellung Schulter'),
                                          ('S20.2', 'Prellung Thorax'),
                                          ('S20.2', 'Prellung Brustwirbelsäule'),
                                          ('S40.0', 'Prellung Oberarm'),
                                          ('S50.0', 'Prellung Ellenbogen'),
                                          ('S50.1', 'Prellung Unterarm'),
                                          ('S60.2', 'Prellung Hand/Finger'),
                                          ('S30.0', 'Prellung Lendenwirbelsäule'),
                                          ('S30.1', 'Prellung Abdomen'),
                                          ('S70.0', 'Prellung Becken/Hüfte'),
                                          ('S30.2', 'Prellung Genitalbereich'),
                                          ('S70.1', 'Prellung Oberschenkel'),
                                          ('S80.0', 'Prellung Knie'),
                                          ('S80.1', 'Prellung Unterschenkel'),
                                          ('S90.0', 'Prellung Knöchel'),
                                          ('S90.3', 'Prellung Fuß/Zehen'),
                                          ('S03.1', 'Luxation Schädel'),
                                          ('S23.2', 'Luxation Augen'),
                                          ('S03.1', 'Luxation Nase'),
                                          ('T03.0', 'Luxation Halswirbelsäule'),
                                          ('S43.3', 'Luxation Schulter'),
                                          ('S23.2', 'Luxation Thorax'),
                                          ('S23.1', 'Luxation Brustwirbelsäule'),
                                          ('S43.3', 'Luxation Oberarm'),
                                          ('S53.1', 'Luxation Ellenbogen'),
                                          ('S53.1', 'Luxation Unterarm'),
                                          ('S63.0', 'Luxation Hand/Finger'),
                                          ('S33.3', 'Luxation Lendenwirbelsäule'),
                                          ('S79.0', 'Luxation Becken/Hüfte'),
                                          ('S73.0', 'Luxation Genitalbereich'),
                                          ('S83.0', 'Luxation Oberschenkel'),
                                          ('S83.0', 'Luxation Knie'),
                                          ('T03.3', 'Luxation Unterschenkel'),
                                          ('T03.3', 'Luxation Knöchel'),
                                          ('S93.0', 'Luxation Fuß/Zehen'),
                                          ('S06.0', 'Commotio Schädel'),
                                          ('S06.0', 'Commotio Augen'),
                                          ('S06.0', 'Commotio Nase'),
                                          ('S06.0', 'Commotio Halswirbelsäule'),
                                          ('S06.0', 'Commotio Schulter'),
                                          ('S06.0', 'Commotio Thorax'),
                                          ('S06.0', 'Commotio Brustwirbelsäule'),
                                          ('S06.0', 'Commotio Oberarm'),
                                          ('S06.0', 'Commotio Ellenbogen'),
                                          ('S06.0', 'Commotio Unterarm'),
                                          ('S06.0', 'Commotio Hand/Finger'),
                                          ('S06.0', 'Commotio Lendenwirbelsäule'),
                                          ('S06.0', 'Commotio Abdomen'),
                                          ('S06.0', 'Commotio Becken/Hüfte'),
                                          ('S06.0', 'Commotio Genitalbereich'),
                                          ('S06.0', 'Commotio Oberschenkel'),
                                          ('S06.0', 'Commotio Knie'),
                                          ('S06.0', 'Commotio Unterschenkel'),
                                          ('S06.0', 'Commotio Knöchel'),
                                          ('S06.0', 'Commotio Fuß/Zehen'),
                                          ('T20.0', 'Verbrennung Schädel'),
                                          ('T20.0', 'Verbrennung Augen'),
                                          ('T20.0', 'Verbrennung Nase'),
                                          ('T20.0', 'Verbrennung Halswirbelsäule'),
                                          ('T22.0', 'Verbrennung Schulter'),
                                          ('T21.0', 'Verbrennung Thorax'),
                                          ('T21.0', 'Verbrennung Brustwirbelsäule'),
                                          ('T22.0', 'Verbrennung Oberarm'),
                                          ('T22.0', 'Verbrennung Ellenbogen'),
                                          ('T22.0', 'Verbrennung Unterarm'),
                                          ('T23.0', 'Verbrennung Hand/Finger'),
                                          ('T21.0', 'Verbrennung Lendenwirbelsäule'),
                                          ('T21.0', 'Verbrennung Abdomen'),
                                          ('T24.0', 'Verbrennung Becken/Hüfte'),
                                          ('T21.0', 'Verbrennung Genitalbereich'),
                                          ('T24.0', 'Verbrennung Oberschenkel'),
                                          ('T24.0', 'Verbrennung Knie'),
                                          ('T24.0', 'Verbrennung Unterschenkel'),
                                          ('T25.0', 'Verbrennung Knöchel'),
                                          ('T25.0', 'Verbrennung Fuß/Zehen');













